// export const foods = [
//   {
//     id: 0,
//     category: 'Entradas',
//     name: 'Ceviche',
//     unityPrice: 12,
//   },
//   {
//     id: 1,
//     category: 'Entradas',
//     name: 'Sunomono',
//     unityPrice: 12,
//   },
//   {
//     id: 2,
//     category: 'Entradas',
//     name: 'Pasta de Atum',
//     unityPrice: 8,
//   },
//   {
//     id: 3,
//     category: 'Entradas',
//     name: 'Carpaccio de Salmão',
//     unityPrice: 18,
//   },
//   {
//     id: 4,
//     category: 'Entradas',
//     name: 'Tartar Crispy',
//     unityPrice: 4,
//   },
//   {
//     id: 5,
//     category: 'Entradas',
//     name: 'Tartar Chips',
//     unityPrice: 4,
//   },
//   {
//     id: 6,
//     category: 'Entradas Quentes',
//     name: 'Guioza',
//     unityPrice: 12,
//   },
//   {
//     id: 7,
//     category: 'Entradas Quentes',
//     name: 'Missoshiro',
//     unityPrice: 12,
//   },
//   {
//     id: 8,
//     category: 'Entradas Quentes',
//     name: 'Lula à dorê',
//     unityPrice: 15,
//   },
//   {
//     id: 9,
//     category: 'Entradas Quentes',
//     name: 'Nuvem Philadelphia Crocante',
//     unityPrice: 10,
//   },
//   {
//     id: 10,
//     category: 'Entradas Quentes',
//     name: 'Bolinho de Salmão',
//     unityPrice: 4,
//   },
//   {
//     id: 11,
//     category: 'Entradas Quentes',
//     name: 'Tempura Mix',
//     unityPrice: 8,
//   },
//   {
//     id: 12,
//     category: 'Entradas Quentes',
//     name: 'Shimeji',
//     unityPrice: 12,
//   },
//   {
//     id: 13,
//     category: 'Harumaki',
//     name: 'Legumes',
//     unityPrice: 4.75,
//   },
//   {
//     id: 14,
//     category: 'Harumaki',
//     name: 'Camarão',
//     unityPrice: 6,
//   },
//   {
//     id: 15,
//     category: 'Harumaki',
//     name: 'Queijo',
//     unityPrice: 5.25,
//   },
//   {
//     id: 16,
//     category: 'Harumaki',
//     name: 'Salmão',
//     unityPrice: 6,
//   },
//   {
//     id: 17,
//     category: 'Sashimi',
//     name: 'Atum',
//     unityPrice: 3.6,
//   },
//   {
//     id: 18,
//     category: 'Sashimi',
//     name: 'Peixe Branco',
//     unityPrice: 3.6,
//   },
//   {
//     id: 19,
//     category: 'Sashimi',
//     name: 'Polvo',
//     unityPrice: 3.7,
//   },
//   {
//     id: 20,
//     category: 'Sashimi',
//     name: 'Haddock',
//     unityPrice: 4,
//   },
//   {
//     id: 21,
//     category: 'Sashimi',
//     name: 'Salmão Roasted',
//     unityPrice: 3.8,
//   },
//   {
//     id: 22,
//     category: 'Sashimi',
//     name: 'Salmão Luxo',
//     unityPrice: 4,
//   },
//   {
//     id: 23,
//     category: 'Sashimi',
//     name: 'Salmão Maracujá',
//     unityPrice: 3.9,
//   },
//   {
//     id: 24,
//     category: 'Sashimi',
//     name: 'Salmão Crispy',
//     unityPrice: 4,
//   },
//   {
//     id: 25,
//     category: 'Sashimi',
//     name: 'Salmão na Crosta',
//     unityPrice: 3.9,
//   },
//   {
//     id: 26,
//     category: 'Sashimi',
//     name: 'Salmão Trufado',
//     unityPrice: 4.1,
//   },
//   {
//     id: 27,
//     category: 'Sashimi',
//     name: 'Atum Roasted',
//     unityPrice: 3.7,
//   },
//   {
//     id: 28,
//     category: 'Joe',
//     name: 'Tradicional',
//     unityPrice: 5.75,
//   },
//   {
//     id: 29,
//     category: 'Joe',
//     name: 'Camarão',
//     unityPrice: 6.75,
//   },
//   {
//     id: 30,
//     category: 'Joe',
//     name: 'Maracujá',
//     unityPrice: 6.25,
//   },
//   {
//     id: 31,
//     category: 'Joe',
//     name: 'Abacaxi',
//     unityPrice: 6.25,
//   },
//   {
//     id: 32,
//     category: 'Joe',
//     name: 'Amora',
//     unityPrice: 6.25,
//   },
//   {
//     id: 33,
//     category: 'Joe',
//     name: 'Lemon',
//     unityPrice: 6.25,
//   },
//   {
//     id: 34,
//     category: 'Joe',
//     name: 'Crispy',
//     unityPrice: 6.5,
//   },
//   {
//     id: 35,
//     category: 'Joe',
//     name: 'Spicy',
//     unityPrice: 6.25,
//   },
//   {
//     id: 36,
//     category: 'Joe',
//     name: 'Roasted',
//     unityPrice: 6.5,
//   },
//   {
//     id: 37,
//     category: 'Sushi',
//     name: 'Salmão',
//     unityPrice: 5.5,
//   },
//   {
//     id: 38,
//     category: 'Sushi',
//     name: 'Atum',
//     unityPrice: 5,
//   },
//   {
//     id: 39,
//     category: 'Sushi',
//     name: 'Peixe Branco',
//     unityPrice: 5,
//   },
//   {
//     id: 40,
//     category: 'Sushi',
//     name: 'Polvo',
//     unityPrice: 6,
//   },
//   {
//     id: 41,
//     category: 'Sushi',
//     name: 'Camarão',
//     unityPrice: 6,
//   },
//   {
//     id: 42,
//     category: 'Sushi',
//     name: 'Salmão Skin',
//     unityPrice: 4.5,
//   },
//   {
//     id: 43,
//     category: 'Sushi',
//     name: 'Salmão Roasted',
//     unityPrice: 6,
//   },
//   {
//     id: 44,
//     category: 'Sushi',
//     name: 'Atum Roasted',
//     unityPrice: 5.5,
//   },
//   {
//     id: 45,
//     category: 'Sushi',
//     name: 'Salmão Cheese',
//     unityPrice: 6,
//   },
//   {
//     id: 46,
//     category: 'Sushi',
//     name: 'Salmão Trufado',
//     unityPrice: 6.5,
//   },
//   {
//     id: 47,
//     category: 'Makimono Roll',
//     name: 'Philadelphia',
//     unityPrice: 3,
//   },
//   {
//     id: 48,
//     category: 'Makimono Roll',
//     name: 'Philadelphia Crocante',
//     unityPrice: 2.4,
//   },
//   {
//     id: 49,
//     category: 'Makimono Roll',
//     name: 'California',
//     unityPrice: 2.6,
//   },
//   {
//     id: 50,
//     category: 'Makimono Roll',
//     name: 'Boston Cheese',
//     unityPrice: 2.4,
//   },
//   {
//     id: 51,
//     category: 'Makimono Roll',
//     name: 'Uramaki Salmão',
//     unityPrice: 3.2,
//   },
//   {
//     id: 52,
//     category: 'Makimono Roll',
//     name: 'Uramaki Crispy',
//     unityPrice: 2.4,
//   },
//   {
//     id: 53,
//     category: 'Makimono Roll',
//     name: 'Uramaki Atum',
//     unityPrice: 2.4,
//   },
//   {
//     id: 54,
//     category: 'Makimono Roll',
//     name: 'Uramaki Skin',
//     unityPrice: 2.4,
//   },
//   {
//     id: 55,
//     category: 'Makimono Roll',
//     name: 'Spicy Tuna',
//     unityPrice: 3,
//   },
//   {
//     id: 56,
//     category: 'Hot Roll',
//     name: 'Philadelphia',
//     unityPrice: 2.8,
//   },
//   {
//     id: 57,
//     category: 'Hot Roll',
//     name: 'Philadelphia Crocante',
//     unityPrice: 2.9,
//   },
//   {
//     id: 58,
//     category: 'Hot Roll',
//     name: 'Philadelphia Abacaxi',
//     unityPrice: 2.9,
//   },
//   {
//     id: 59,
//     category: 'Hot Roll',
//     name: 'Philadelphia Tartar',
//     unityPrice: 2.9,
//   },
//   {
//     id: 60,
//     category: 'Hot Roll',
//     name: 'Philadelphia Crispy',
//     unityPrice: 2.9,
//   },
//   {
//     id: 61,
//     category: 'Hot Roll',
//     name: 'Philadelphia Spicy',
//     unityPrice: 2.9,
//   },
//   {
//     id: 62,
//     category: 'Hot Roll',
//     name: 'Camarão',
//     unityPrice: 3,
//   },
//   {
//     id: 63,
//     category: 'Hot Roll',
//     name: 'Haddock Croc',
//     unityPrice: 2.9,
//   },
//   {
//     id: 64,
//     category: 'Hot Roll',
//     name: 'Haru',
//     unityPrice: 2.9,
//   },
//   {
//     id: 65,
//     category: 'Hot Roll',
//     name: 'Haru Skin',
//     unityPrice: 2.8,
//   },
//   {
//     id: 66,
//     category: 'Temaki',
//     name: 'Philadelphia',
//     unityPrice: 14.5,
//   },
//   {
//     id: 676,
//     category: 'Temaki',
//     name: 'Salmão Crispy',
//     unityPrice: 16.5,
//   },
//   {
//     id: 68,
//     category: 'Temaki',
//     name: 'Atum',
//     unityPrice: 13.5,
//   },
//   {
//     id: 69,
//     category: 'Temaki',
//     name: 'Atum Temperado',
//     unityPrice: 14.5,
//   },
//   {
//     id: 70,
//     category: 'Temaki',
//     name: 'Camarão',
//     unityPrice: 15,
//   },
//   {
//     id: 71,
//     category: 'Temaki',
//     name: 'Camarão Crispy',
//     unityPrice: 17,
//   },
//   {
//     id: 72,
//     category: 'Temaki',
//     name: 'California',
//     unityPrice: 13.5,
//   },
//   {
//     id: 73,
//     category: 'Temaki',
//     name: 'Philadelphia Hot',
//     unityPrice: 15.5,
//   },
//   {
//     id: 74,
//     category: 'Temaki',
//     name: 'Hot Crocante',
//     unityPrice: 15,
//   },
//   {
//     id: 75,
//     category: 'Sobremesas',
//     name: 'Harumaki de Chocolate',
//     unityPrice: 5,
//   },
//   {
//     id: 76,
//     category: 'Sobremesas',
//     name: 'Harumaki de Chocolate Branco',
//     unityPrice: 5,
//   },
//   {
//     id: 77,
//     category: 'Sobremesas',
//     name: 'Harumaki de Banana',
//     unityPrice: 5,
//   },
//   {
//     id: 78,
//     category: 'Sobremesas',
//     name: 'Harumaki Romeu e Julieta',
//     unityPrice: 5,
//   },
//   {
//     id: 79,
//     category: 'Sobremesas',
//     name: 'Roll de Banana',
//     unityPrice: 2,
//   },
//   {
//     id: 80,
//     category: 'Sobremesas',
//     name: 'Brownie',
//     unityPrice: 5,
//   },
//   {
//     id: 81,
//     category: 'Sobremesas',
//     name: 'Bola de sorvete',
//     unityPrice: 3,
//   },
// ];

export const foods = [
  { id: 0, category: 'Entradas', name: 'Sunomono', unityPrice: 1 },
  { id: 1, category: 'Entradas', name: 'Shimeji e Shitake', unityPrice: 1 },
  { id: 2, category: 'Entradas', name: 'Shimeji', unityPrice: 1 },
  { id: 3, category: 'Entradas', name: 'Shitake', unityPrice: 1 },
  { id: 4, category: 'Entradas', name: 'Kakiague', unityPrice: 1 },
  { id: 5, category: 'Entradas', name: 'Harumaki de Camarão', unityPrice: 1 },
  { id: 6, category: 'Entradas', name: 'Camarão Empanado', unityPrice: 1 },
  { id: 7, category: 'Entradas', name: 'Nirá', unityPrice: 1 },
  { id: 8, category: 'Entradas', name: 'Guioza Suíno', unityPrice: 1 },
  { id: 9, category: 'Entradas', name: 'Kakiague de Milho', unityPrice: 1 },
  { id: 10, category: 'Entradas', name: 'Edamame', unityPrice: 1 },
  { id: 11, category: 'Entradas', name: 'Harumaki de Legumes', unityPrice: 1 },
  { id: 12, category: 'Entradas', name: 'Robata de Carne', unityPrice: 1 },
  { id: 13, category: 'Entradas', name: 'Robata de Camarão', unityPrice: 1 },
  { id: 14, category: 'Entradas', name: 'Robata de Lula', unityPrice: 1 },
  { id: 15, category: 'Entradas', name: 'Isca de Tilápia', unityPrice: 1 },
  { id: 16, category: 'Entradas', name: 'Casquinha de Salmão', unityPrice: 1 },
  { id: 17, category: 'Entradas', name: 'Ika no Furai', unityPrice: 1 },
  { id: 18, category: 'Entradas', name: 'Croqueta de Polvo', unityPrice: 1 },
  { id: 19, category: 'Entradas', name: 'Dadinho de Tapioca', unityPrice: 1 },
  { id: 20, category: 'Entradas', name: 'Bolinho de Salmão', unityPrice: 1 },

  { id: 21, category: 'Marinados', name: 'Marinado Trufado', unityPrice: 1 },
  { id: 22, category: 'Marinados', name: 'Sashimi Roasted no Alho', unityPrice: 1 },
  { id: 23, category: 'Marinados', name: 'Marinado de Ervas', unityPrice: 1 },
  { id: 24, category: 'Marinados', name: 'Marinado de Salmão com Alcaparras', unityPrice: 1 },
  { id: 25, category: 'Marinados', name: 'Marinado de Polvo', unityPrice: 1 },
  { id: 26, category: 'Marinados', name: 'Marinado Saint Peter', unityPrice: 1 },

  { id: 27, category: 'Hot Rolls', name: 'Mini-Hot Couve', unityPrice: 1 },
  { id: 28, category: 'Hot Rolls', name: 'Mini-Hot Spicy', unityPrice: 1 },
  { id: 29, category: 'Hot Rolls', name: 'Hot Salmão Philadelphia', unityPrice: 1 },
  { id: 30, category: 'Hot Rolls', name: 'Mauro Naves', unityPrice: 1 },
  { id: 31, category: 'Hot Rolls', name: 'Mini-Hot Crispy', unityPrice: 1 },
  { id: 32, category: 'Hot Rolls', name: 'Mini-Hot Rapadura', unityPrice: 1 },
  { id: 33, category: 'Hot Rolls', name: 'Mini-Hot Camarão', unityPrice: 1 },

  { id: 34, category: 'Yakissoba', name: 'Carne e Frango', unityPrice: 1 },
  { id: 35, category: 'Yakissoba', name: 'Camarão', unityPrice: 1 },
  { id: 36, category: 'Yakissoba', name: 'Legumes', unityPrice: 1 },
  { id: 37, category: 'Yakissoba', name: 'Frango', unityPrice: 1 },
  { id: 38, category: 'Yakissoba', name: 'Carne', unityPrice: 1 },

  { id: 39, category: 'Teppan', name: 'Salmão', unityPrice: 1 },

  { id: 40, category: 'Sashimi', name: 'Atum', unityPrice: 1 },
  { id: 41, category: 'Sashimi', name: 'Salmão', unityPrice: 1 },
  { id: 42, category: 'Sashimi', name: 'Peixe Branco', unityPrice: 1 },
  { id: 43, category: 'Sashimi', name: 'Polvo', unityPrice: 1 },
  { id: 44, category: 'Sashimi', name: 'Haddock', unityPrice: 1 },

  { id: 45, category: 'Sushi', name: 'Sushi Camarão', unityPrice: 1 },
  { id: 46, category: 'Sushi', name: 'Sushi Salmão Trufado', unityPrice: 1 },
  { id: 47, category: 'Sushi', name: 'Sushi Salmão', unityPrice: 1 },
  { id: 48, category: 'Sushi', name: 'Sushi Salmão Selado no Alho', unityPrice: 1 },
  { id: 49, category: 'Sushi', name: 'Sushi Salmão Skin', unityPrice: 1 },
  { id: 50, category: 'Sushi', name: 'Sushi Atum', unityPrice: 1 },
  { id: 51, category: 'Sushi', name: 'Sushi Peixe Branco', unityPrice: 1 },
  { id: 52, category: 'Sushi', name: 'Sushi Skin Naves', unityPrice: 1 },
  { id: 53, category: 'Sushi', name: 'Sushi de Saint Peter Maçaricado', unityPrice: 1 },
  { id: 54, category: 'Sushi', name: 'Sushi de Polvo', unityPrice: 1 },

  { id: 55, category: 'Temaki', name: 'Salmão', unityPrice: 1 },
  { id: 56, category: 'Temaki', name: 'Salmão Completo', unityPrice: 1 },
  { id: 57, category: 'Temaki', name: 'Atum', unityPrice: 1 },
  { id: 58, category: 'Temaki', name: 'Atum Completo', unityPrice: 1 },
  { id: 59, category: 'Temaki', name: 'Temaki do Chef', unityPrice: 1 },
  { id: 60, category: 'Temaki', name: 'Super-Hot', unityPrice: 1 },

  { id: 61, category: 'Gunkas', name: 'Gunka Shakê Negui', unityPrice: 1 },
  { id: 62, category: 'Gunkas', name: 'Gunka Crunchy', unityPrice: 1 },
  { id: 63, category: 'Gunkas', name: 'Gunka Crispy', unityPrice: 1 },
  { id: 64, category: 'Gunkas', name: 'Gunka Luka', unityPrice: 1 },
  { id: 65, category: 'Gunkas', name: 'Gunka Massagô', unityPrice: 1 },
  { id: 66, category: 'Gunkas', name: 'Gunka Rapadura', unityPrice: 1 },
  { id: 67, category: 'Gunkas', name: 'Gunka Ebi Furai', unityPrice: 1 },
  { id: 68, category: 'Gunkas', name: 'Gunka Couve', unityPrice: 1 },
  { id: 69, category: 'Gunkas', name: 'Gunka Pistache', unityPrice: 1 },
  { id: 70, category: 'Gunkas', name: 'Gunka Abacaxi', unityPrice: 1 },

  { id: 71, category: 'Rolls', name: 'Hossomaki Filadélfia', unityPrice: 1 },
  { id: 72, category: 'Rolls', name: 'Uramaki Filadélfia', unityPrice: 1 },
  { id: 73, category: 'Rolls', name: 'Uramaki Califórnia', unityPrice: 1 },
  { id: 74, category: 'Rolls', name: 'Uramaki Ebiten', unityPrice: 1 },
  { id: 75, category: 'Rolls', name: 'Uramaki Salmão', unityPrice: 1 },
  { id: 76, category: 'Rolls', name: 'Uramaki Atum', unityPrice: 1 },
  { id: 77, category: 'Rolls', name: 'Hossomaki Salmão', unityPrice: 1 },
  { id: 78, category: 'Rolls', name: 'Hossomaki Atum', unityPrice: 1 },
  { id: 79, category: 'Rolls', name: 'Uramaki de Salmão Especial', unityPrice: 1 },

  { id: 80, category: 'Sobremesa', name: 'Bola de Sorvete', unityPrice: 1 },
  { id: 81, category: 'Sobremesa', name: 'Hot Banana com Nutella', unityPrice: 1 },
  { id: 82, category: 'Sobremesa', name: 'Mini Banana Flambada', unityPrice: 1 },
  { id: 83, category: 'Sobremesa', name: 'Harumaki de Chocolate', unityPrice: 1 },
  { id: 84, category: 'Sobremesa', name: 'Petit Gateau', unityPrice: 1 },
  { id: 85, category: 'Sobremesa', name: 'Harumaki de Creme de Avelã', unityPrice: 1 },
  { id: 86, category: 'Sobremesa', name: 'Brownie do Luiz com Sorvete', unityPrice: 1 },
  { id: 87, category: 'Sobremesa', name: 'Harumaki de Chocolate Branco', unityPrice: 1 },
];